# Generated by Django 3.0.4 on 2020-04-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscalName', models.CharField(max_length=100)),
                ('commercialName', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('postalCode', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['fiscalName'],
            },
        ),
        migrations.CreateModel(
            name='CompanyConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=20)),
                ('primaryColor', models.CharField(max_length=20)),
                ('secondaryColor', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/%Y/%m')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp.Company')),
            ],
            options={
                'ordering': ['shortName'],
            },
        ),
    ]
