# Generated by Django 3.0.4 on 2020-04-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
