# Generated by Django 3.0.4 on 2020-04-01 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconfiguration',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='configuration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.CompanyConfiguration'),
        ),
    ]
