# Generated by Django 3.0.4 on 2020-04-02 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_company_isactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyconfiguration',
            options={},
        ),
    ]
