# Generated by Django 3.0.4 on 2020-04-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='lastAccess',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
