# Generated by Django 3.0.4 on 2020-04-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_token_lastaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
    ]
