
query items{
  companies{
    id
    fiscalName
    commercialName
    nif
    email
    website
    telephone
    mobile
    address
    postalCode
    isActive
    companyconfiguration{
      id
      shortName
    }
  }
}
